#version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: weather_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=weather_service
    volumes:
      - mongodb_data:/data/db
    networks:
      - weather_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: weather_app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - weather_network

networks:
  weather_network:
    driver: bridge

volumes:
  mongodb_data: